(define (30) (rem print "'ignored'"))
(define (35) (void))
(define (50) (print "never gets here"))
(define (40) (end))
(define (60) (print "three") (print (+ 1.0 3)))
(define (70) (goto (+ 11 18.5 0.5)) (rem "ignored"))
(define (10) (print "o" "n" "e"))
(define (20) (print) (goto 60) (end))